export const brands: { [key: string]: string[] } = {
  Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8'],
  BMW: ['1 серия', '3 серия', '5 серия', 'X1', 'X3', 'X5'],
  Chevrolet: ['Aveo', 'Captiva', 'Cruze', 'Epica', 'Lacetti'],
  Ford: ['C-MAX', 'EcoSport', 'Fiesta', 'Focus', 'Kuga', 'Mondeo', 'Transit'],
  Honda: ['Accord', 'Civic', 'Crosstour', 'CR-V'],
  Hyundai: ['Creta', 'Elantra', 'i30', 'i40', 'ix35', 'Santa Fe', 'Solaris', 'Sonata', 'Tucson'],
  Infiniti: ['EX25', 'EX35', 'FX35', 'FX37', 'QX56'],
  Kia: ['Ceed', 'Cerato', 'K5', 'Optima', 'Rio', 'Sorento', 'Soul', 'Sportage'],
  Mazda: ['3', '5', '6', 'CX-5', 'CX-7'],
  'Mercedes-Benz': ['C-класс', 'E-класс', 'GLA-класс', 'GLK-класс', 'GL-класс', 'M-класс', 'Sprinter', 'S-класс'],
  Mitsubishi: ['ASX', 'Galant', 'L200', 'Lancer', 'Outlander', 'Pajero', 'Pajero Sport'],
  Nissan: ['Almera', 'Juke', 'Murano', 'Navara', 'Note', 'Pathfinder', 'Patrol', 'Primera', 'Qashqai', 'Teana', 'Tiida', 'X-Trail'],
  Opel: ['Antara', 'Astra', 'Insignia', 'Mokka', 'Zafira'],
  Peugeot: ['206', '207', '307', '308', '407', '408', 'Partner'],
  Renault: ['Arkana', 'Duster', 'Fluence', 'Kaptur', 'Logan', 'Megane', 'Sandero'],
  SsangYong: ['Actyon', 'Actyon Sports', 'Kyron', 'Rexton'],
  Skoda: ['Fabia', 'Karoq', 'Octavia', 'Rapid', 'Superb', 'Yeti'],
  Subaru: ['Forester', 'Impreza', 'Legacy', 'Outback', 'XV'],
  Suzuki: ['Grand Vitara', 'Jimny', 'Liana', 'SX4', 'Vitara'],
  Toyota: ['Auris', 'Avensis', 'Camry', 'Corolla', 'Highlander', 'Hilux', 'Land Cruiser', 'Land Cruiser Prado', 'RAV4', 'Venza', 'Yaris'],
  Volkswagen: ['Caravelle', 'Golf', 'Jetta', 'Multivan', 'Passat', 'Passat CC', 'Polo', 'Scirocco', 'Tiguan', 'Touareg', 'Touran', 'Transporter'],
  Volvo: ['S40', 'S60', 'S80', 'XC60', 'XC70', 'XC90'],
  'ВАЗ (LADA)': [
    '2101',
    '2104',
    '2105',
    '2106',
    '2107',
    '2109',
    '21099',
    '2110',
    '2111',
    '2112',
    '2113 Samara',
    '2114 Samara',
    '2115 Samara',
    '4x4 (Нива)',
    'Granta',
    'Kalina',
    'Largus',
    'Priora',
    'Vesta',
    'XRAY',
  ],
  ГАЗ: ['Волга', 'ГАЗель', 'Соболь'],
  УАЗ: ['3151', '3909', '469', 'Hunter', 'Patriot', 'Профи'],
}
